[package]
authors = ["Daniel Woznicki <daniel.woznicki@gmail.com>"]
description = "Macro for SerializeUnion."
edition = "2018"
license = "Apache-2.0/MIT"
name = "swc_babel_compat_macros"
repository = "https://github.com/swc-project/swc.git"
version = "0.1.0"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.7"
syn = {version = "1.0.54", features = ["extra-traits"]}
